Suppress octokit deprecation warning
Naturalclar/klank pull request #37
Opened 2020-01-17 07:09 UTC by tatsushitoji

Hello Naturalclar :wave: 
I'm a big fan of moxci and noticed deprecation warning when used on CircleCI.
just below:

```
Deprecation: [@octokit/rest] "number" parameter is deprecated for ".issues.createComment()". Use "issue_number" instead
  …
  at Object.exports.notifyGithubPr (/home/circleci/some_repo/node_modules/moxci/lib/github-notify.js:42:12) {
  name: 'Deprecation'
}
```

The `number` parameter has been deprecated and seems to have been changed to an `issue_number`.
So I tried some fixes. Please review.

2020-01-17 07:11 UTC, tatsushitoji commented on src/github-notify.ts
> +    console.error("Invalid Pull Request Id");
There may be more correct error messages 🤔

2020-01-21 03:38 UTC, Naturalclar requested changes
@tatsushitoji Thanks for the PR!
I'd like to have the rename and error logic to be in `index.ts` instead of `github-notify.ts`

Could you rename the input of `github-notify.ts` from `number` to `issue_number`,

and add the validation in index.ts https://github.com/moxci/moxci/blob/master/src/index.ts#L60 ?

2020-01-21 05:46 UTC, tatsushitoji commented
thx for review.

I agree with 
> to have the rename and error logic to be in index.ts instead of github-notify.ts

I just wanted to hear the intention of the owner :grin:
I'll fix it.

2020-01-21 06:24 UTC, tatsushitoji commented on src/index.ts
> +    const pullRequestId = Number(CIRCLE_PULL_REQUEST.split("/").pop());
`issue_number` argument of `octokit.issues.createComment` expects a number type, so converting to a number type here.

2020-01-21 07:32 UTC, Naturalclar approved these changes
LGTM! thank you for your contribution!

2020-01-21 07:32 UTC, merged